import '@coinbase/onchainkit/styles.css';
import type { Metadata } from 'next';

import './globals.css';
import Navigation from './components/Navigation';
import { Providers, SmartWalletOnlyProvider } from './providers';

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
  description:
    'Generated by `create-onchain`, a Next.js template for OnchainKit',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark bg-background">
        <SmartWalletOnlyProvider>
          <Providers>
            <Navigation />
            {children}
          </Providers>
        </SmartWalletOnlyProvider>
      </body>
    </html>
  );
}
